//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IO_Products
    {
        public int ProductId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> IncomeDate { get; set; }
        public Nullable<System.DateTime> OutComeDate { get; set; }
    }
}
