//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnProductsList
    {
        public int OwnProductsListId { get; set; }
        public int Number { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
    }
}
