//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerRequest
    {
        public int PartnerRequestId { get; set; }
        public string RequestKind { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> PartnerRefId { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
